#!/usr/bin/env bash
push () 
{ 
    local loc_ip=;
    case "$(hostname)" in 
        unforswearing-b.local)
            loc_ip="100.118.230.76"
        ;;
        unforswearing-original.local)
            loc_ip="100.95.96.84"
        ;;
    esac;
    git push && ssh ${loc_ip} "cd $HOME/zsh-config && git pull && direnv allow && exec zsh"
}
push
